version: "3.9"
services:
  #container 3
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: spring_014_db_mcsv_user
    volumes:
      - data-mysql:/var/lib/mysql
    #restart: always
    networks:
      - spring-kubernetes
  #container 1
  mcsv-users-container:
    container_name: mcsv-users-container
    image: daniella03/mcsv-user
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_HOST: mysql8
      DB_DATABASE: spring_014_db_mcsv_user
      DB_USERNAME: root
      DB_PASSWORD: 1234
      COURSE_URL: http://ec2-18-222-239-213.us-east-2.compute.amazonaws.com:8082
    networks:
        - spring-kubernetes
    #this container depends on mysql8
    depends_on:
        - mysql8
    #restart: always

volumes:
  data-mysql:
    name: data-mysql

#define networks
networks:
  spring-kubernetes:
    name: spring-kubernetes
