apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-deployment
  labels:
    app: hola-deployment
spec:
  selector:
    matchLabels:
      app: hola-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: hola-deployment
    spec:
      containers:
      - name: hola-deployment
        image: daniella03/hola-mundo:latest
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: hola-service
spec:
  type: LoadBalancer
  selector:
    app: hola-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  