apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
      - image: postgres:15-alpine
        name: postgres14
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "1234"
          - name: POSTGRES_DB
            value: "spring_001_db_mcsv_course"
