apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres14
  template:
    metadata:
      labels:
        app: postgres14
    spec:
      containers:
      - image: postgres:15-alpine
        name: postgres14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mcsv-courses-container
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: mcsv-courses-container
              key: database
        volumeMounts:
        - name: data-postgres
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data-postgres
        persistentVolumeClaim:
          claimName: postgres-pvc
