apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcsv-gateway-container
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mcsv-gateway-container
  template:
    metadata:
      labels:
        role: mcsv-gateway-container
    spec:
      containers:
      - name: mcsv-gateway-container
        image: daniella03/mcsv-gateway:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: mcsv-gateway-container
spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
    selector:
        role: mcsv-gateway-container
    type: LoadBalancer
