apiVersion: v1
kind: Service
metadata:
  name: mcsv-courses-container
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: mcsv-courses-container
  type: LoadBalancer